export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED";

export const ARCHIVE_PRODUCT_REQUEST = "ARCHIVE_PRODUCT_REQUEST";
export const ARCHIVE_PRODUCT_SUCCESS = "ARCHIVE_PRODUCT_SUCCESS";
export const ARCHIVE_PRODUCT_FAILED = "ARCHIVE_PRODUCT_FAILED";

export const FETCH_CURRENT_PRODUCT_REQUEST = "FETCH_CURRENT_PRODUCT_REQUEST";
export const FETCH_CURRENT_PRODUCT_SUCCESS = "FETCH_CURRENT_PRODUCT_SUCCESS";
export const FETCH_CURRENT_PRODUCT_FAILED = "FETCH_CURRENT_PRODUCT_FAILED";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const FETCH_CURRENT_PRODUCT_ARTICLES_BY_CATEGORY_REQUEST =
  "FETCH_CURRENT_PRODUCT_ARTICLES_BY_CATEGORY_REQUEST";
export const FETCH_CURRENT_PRODUCT_ARTICLES_BY_CATEGORY_SUCCESS =
  "FETCH_CURRENT_PRODUCT_ARTICLES_BY_CATEGORY_SUCCESS";
export const FETCH_CURRENT_PRODUCT_ARTICLES_BY_CATEGORY_FAILED =
  "FETCH_CURRENT_PRODUCT_ARTICLES_BY_CATEGORY_FAILED";

export const CHANGE_PRODUCT_STATUS_REQUEST = "CHANGE_PRODUCT_STATUS_REQUEST";
export const CHANGE_PRODUCT_STATUS_SUCCESS = "CHANGE_PRODUCT_STATUS_SUCCESS";
export const CHANGE_PRODUCT_STATUS_FAILED = "CHANGE_PRODUCT_STATUS_FAILED";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAILED = "NEW_PRODUCT_FAILED";

export const SET_STATUS_CHANGE_FORM_DISABLE = "SET_STATUS_CHANGE_FORM_DISABLE";
