export const GET_TOKEN_PARAMS = "GET_TOKEN_PARAMS";
export const VERIFY_REGISTRATION_TOKEN_REQUEST =
    "VERIFY_REGISTRATION_TOKEN_REQUEST";
export const VERIFY_REGISTRATION_TOKEN_SUCCESS =
    "VERIFY_REGISTRATION_TOKEN_SUCCESS";
export const VERIFY_REGISTRATION_TOKEN_FAILED =
    "VERIFY_REGISTRATION_TOKEN_FAILED";

export const RESEND_EMAIL_LINK_REQUEST = "RESEND_EMAIL_LINK_REQUEST";
export const RESEND_EMAIL_LINK_SUCCESS = "RESEND_EMAIL_LINK_SUCCESS";
export const RESEND_EMAIL_LINK_FAILED = "RESEND_EMAIL_LINK_FAILED";

export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";

export const REQUEST_ACCOUNT = "REQUEST_ACCOUNT";
export const REQUEST_ACCOUNT_SUCCESS = "REQUEST_ACCOUNT_SUCCESS";
export const REQUEST_ACCOUNT_ERROR = "REQUEST_ACCOUNT_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
export const GET_AUTH_FAILURE = "GET_AUTH_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const DISCONNECT_THE_USER = "DISCONNECT_THE_USER";
export const CONNECT_THE_USER = "CONNECT_THE_USER";
