export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED";

export const CHANGE_EVENT_STATUS_REQUEST = "CHANGE_EVENT_STATUS_REQUEST";
export const CHANGE_EVENT_STATUS_SUCCESS = "CHANGE_EVENT_STATUS_SUCCESS";
export const CHANGE_EVENT_STATUS_FAILED = "CHANGE_EVENT_STATUS_FAILED";

export const FETCH_CURRENT_EVENT_REQUEST = "FETCH_CURRENT_EVENT_REQUEST";
export const FETCH_CURRENT_EVENT_SUCCESS = "FETCH_CURRENT_EVENT_SUCCESS";
export const FETCH_CURRENT_EVENT_FAILED = "FETCH_CURRENT_EVENT_FAILED";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAILED = "UPDATE_EVENT_FAILED";

export const CREATE_EVENT_HEADING_REQUEST = "CREATE_EVENT_HEADING_REQUEST";
export const CREATE_EVENT_HEADING_SUCCESS = "CREATE_EVENT_HEADING_SUCCESS";
export const CREATE_EVENT_HEADING_FAILED = "CREATE_EVENT_HEADING_FAILED";

export const RENAME_EVENT_HEADING_REQUEST = "RENAME_EVENT_HEADING_REQUEST";
export const RENAME_EVENT_HEADING_SUCCESS = "RENAME_EVENT_HEADING_SUCCESS";
export const RENAME_EVENT_HEADING_FAILED = "RENAME_EVENT_HEADING_FAILED";

export const DELETE_EVENT_HEADING_REQUEST = "DELETE_EVENT_HEADING_REQUEST";
export const DELETE_EVENT_HEADING_SUCCESS = "DELETE_EVENT_HEADING_SUCCESS";
export const DELETE_EVENT_HEADING_FAILED = "DELETE_EVENT_HEADING_FAILED";

export const CREATE_EVENT_HEADING_VIDEO_REQUEST =
  "CREATE_EVENT_HEADING_VIDEO_REQUEST";
export const CREATE_EVENT_HEADING_VIDEO_SUCCESS =
  "VIDEO_CREATE_EVENT_HEADING_VIDEO_SUCCESS";
export const CREATE_EVENT_HEADING_VIDEO_FAILED =
  "CREATE_EVENT_HEADING_VIDEO_FAILED";

export const DELETE_EVENT_HEADING_VIDEO_REQUEST =
  "DELETE_EVENT_HEADING_VIDEO_REQUEST";
export const DELETE_EVENT_HEADING_VIDEO_SUCCESS =
  "DELETE_EVENT_HEADING_VIDEO_SUCCESS";
export const DELETE_EVENT_HEADING_VIDEO_FAILED =
  "DELETE_EVENT_HEADING_VIDEO_FAILED";

export const SET_SELECTED_VIDEO = "SET_SELECTED_VIDEO";
export const CLEAR_CURRENT_VIDEO = "CLEAR_CURRENT_VIDEO";

export const UPDATE_EVENT_HEADING_VIDEO_REQUEST =
  "UPDATE_EVENT_HEADING_VIDEO_REQUEST";
export const UPDATE_EVENT_HEADING_VIDEO_SUCCESS =
  "UPDATE_EVENT_HEADING_VIDEO_SUCCESS";
export const UPDATE_EVENT_HEADING_VIDEO_FAILED =
  "UPDATE_EVENT_HEADING_VIDEO_FAILED";

export const SET_SELECTED_HEADING = "SET_SELECTED_HEADING";
export const CLEAR_SELECTED_HEADING = " CLEAR_SELECTED_HEADING";

export const FEATURE_EVENT_REQUEST = "FEATURE_EVENT_REQUEST";
export const FEATURE_EVENT_SUCCESS = "FEATURE_EVENT_SUCCESS";
export const FEATURE_EVENT_FAILED = "FEATURE_EVENT_FAILED";

export const SET_STATUS_CHANGE_FORM_DISABLE = "SET_STATUS_CHANGE_FORM_DISABLE";
