export const FETCH_VERIFIED_ADMINS_REQUEST = "FETCH_VERIFIED_ADMINS_REQUEST";
export const FETCH_VERIFIED_ADMINS_SUCCESS = "FETCH_VERIFIED_ADMINS_SUCCESS";
export const FETCH_VERIFIED_ADMINS_FAILED = "FETCH_VERIFIED_ADMINS_FAILED";

export const FETCH_ADMIN_REQUEST_LIST = "FETCH_ADMIN_REQUEST_LIST";
export const FETCH_ADMIN_REQUEST_LIST_SUCCESS =
    "FETCH_ADMIN_REQUEST_LIST_SUCCESS";
export const FETCH_ADMIN_REQUEST_LIST_FAILED =
    "FETCH_ADMIN_REQUEST_LIST_FAILED";

export const CREATE_ADMIN_REQUEST = "CREATE_ADMIN_REQUEST";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_FAILED = "CREATE_ADMIN_FAILED";

export const UPDATE_ADMIN_REQUEST = "UPDATE_ADMIN_REQUEST";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_FAILED = "UPDATE_ADMIN_FAILED";

export const DELETE_ADMIN_REQUEST = "DELETE_ADMIN_REQUEST";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_FAILED = "DELETE_ADMIN_FAILED";

export const UNDO_DELETE_ADMIN_REQUEST = "UNDO_DELETE_ADMIN_REQUEST";
export const UNDO_DELETE_ADMIN_SUCCESS = "UNDO_DELETE_ADMIN_SUCCESS";
export const UNDO_DELETE_ADMIN_FAILED = "UNDO_DELETE_ADMIN_FAILED";

export const FETCH_CURRENT_ADMIN_REQUEST = "FETCH_CURRENT_ADMIN_REQUEST";
export const FETCH_CURRENT_ADMIN_SUCCESS = "FETCH_CURRENT_ADMIN_SUCCESS";
export const FETCH_CURRENT_ADMIN_FAILED = "FETCH_CURRENT_ADMIN_FAILED";

export const FETCH_SITE_USERS_REQUEST = "FETCH_SITE_USERS_REQUEST";
export const FETCH_SITE_USERS_SUCCESS = "FETCH_SITE_USERS_SUCCESS";
export const FETCH_SITE_USERS_FAILED = "FETCH_SITE_USERS_FAILED";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const UNDO_DELETE_USER_REQUEST = "UNDO_DELETE_USER_REQUEST";
export const UNDO_DELETE_USER_SUCCESS = "UNDO_DELETE_USER_SUCCESS";
export const UNDO_DELETE_USER_FAILED = "UNDO_DELETE_USER_FAILED";

export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAILED = "FETCH_CURRENT_USER_FAILED";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const FETCH_INVITED_SITE_USERS_REQUEST =
    "FETCH_INVITED_SITE_USERS_REQUEST";
export const FETCH_INVITED_SITE_USERS_SUCCESS =
    "FETCH_INVITED_SITE_USERS_SUCCESS";
export const FETCH_INVITED_SITE_USERS_FAILED =
    "FETCH_INVITED_SITE_USERS_FAILED";

export const UNLOCK_ADMIN_REQUEST = "UNLOCK_ADMIN_REQUEST";
export const UNLOCK_ADMIN_SUCCESS = "UNLOCK_ADMIN_SUCCESS";
export const UNLOCK_ADMIN_FAILED = "UNLOCK_ADMIN_FAILED";

export const UNLOCK_USER_REQUEST = "UNLOCK_USER_REQUEST";
export const UNLOCK_USER_SUCCESS = "UNLOCK_USER_SUCCESS";
export const UNLOCK_USER_FAILED = "UNLOCK_USER_FAILED";

export const BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAILED = "BLOCK_USER_FAILED";
