export const FETCH_VERIFIED_ADMINS_REQUEST = "FETCH_VERIFIED_ADMINS_REQUEST";
export const FETCH_VERIFIED_ADMINS_SUCCESS = "FETCH_VERIFIED_ADMINS_SUCCESS";
export const FETCH_VERIFIED_ADMINS_FAILED = "FETCH_VERIFIED_ADMINS_FAILED";

export const FETCH_ADMIN_REQUEST_LIST = "FETCH_ADMIN_REQUEST_LIST";
export const FETCH_ADMIN_REQUEST_LIST_SUCCESS =
  "FETCH_ADMIN_REQUEST_LIST_SUCCESS";
export const FETCH_ADMIN_REQUEST_LIST_FAILED =
  "FETCH_ADMIN_REQUEST_LIST_FAILED";

export const CREATE_ADMIN_REQUEST = "CREATE_ADMIN_REQUEST";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_FAILED = "CREATE_ADMIN_FAILED";

export const UPDATE_ADMIN_REQUEST = "UPDATE_ADMIN_REQUEST";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_FAILED = "UPDATE_ADMIN_FAILED";

export const DELETE_ADMIN_REQUEST = "DELETE_ADMIN_REQUEST";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_FAILED = "DELETE_ADMIN_FAILED";

export const FETCH_CURRENT_ADMIN_REQUEST = "FETCH_CURRENT_ADMIN_REQUEST";
export const FETCH_CURRENT_ADMIN_SUCCESS = "FETCH_CURRENT_ADMIN_SUCCESS";
export const FETCH_CURRENT_ADMIN_FAILED = "FETCH_CURRENT_ADMIN_FAILED";
