export const FETCH_MONTHLY_USERS_COUNT_REQUEST =
    "FETCH_MONTHLY_USERS_COUNT_REQUEST";
export const FETCH_MONTHLY_USERS_COUNT_SUCCESS =
    "FETCH_MONTHLY_USERS_COUNT_SUCCESS";
export const FETCH_MONTHLY_USERS_COUNT_FAILED =
    "FETCH_MONTHLY_USERS_COUNT_FAILED";

export const FETCH_TOTAL_ACTIVE_DOCTORS_REQUEST =
    "FETCH_TOTAL_ACTIVE_DOCTORS_REQUEST";
export const FETCH_TOTAL_ACTIVE_DOCTORS_SUCCESS =
    "FETCH_TOTAL_ACTIVE_DOCTORS_SUCCESS";
export const FETCH_TOTAL_ACTIVE_DOCTORS_FAILED =
    "FETCH_TOTAL_ACTIVE_DOCTORS_FAILED";

export const FETCH_TOTAL_BLOCKED_DOCTORS_REQUEST =
    "FETCH_TOTAL_BLOCKED_DOCTORS_REQUEST";
export const FETCH_TOTAL_BLOCKED_DOCTORS_SUCCESS =
    "FETCH_TOTAL_BLOCKED_DOCTORS_SUCCESS";
export const FETCH_TOTAL_BLOCKED_DOCTORS_FAILED =
    "FETCH_TOTAL_BLOCKED_DOCTORS_FAILED";

export const FETCH_TOTAL_ACTIVE_ADMINS_REQUEST =
    "FETCH_TOTAL_ACTIVE_ADMINS_REQUEST";
export const FETCH_TOTAL_ACTIVE_ADMINS_SUCCESS =
    "FETCH_TOTAL_ACTIVE_ADMINS_SUCCESS";
export const FETCH_TOTAL_ACTIVE_ADMINS_FAILED =
    "FETCH_TOTAL_ACTIVE_ADMINS_FAILED";

export const FETCH_TOTAL_BLOCKED_ADMINS_REQUEST =
    "FETCH_TOTAL_BLOCKED_ADMINS_REQUEST";
export const FETCH_TOTAL_BLOCKED_ADMINS_SUCCESS =
    "FETCH_TOTAL_BLOCKED_ADMINS_SUCCESS";
export const FETCH_TOTAL_BLOCKED_ADMINS_FAILED =
    "FETCH_TOTAL_BLOCKED_ADMINS_FAILED";

export const FETCH_TOTAL_CATEGORIES_REQUEST = "FETCH_TOTAL_CATEGORIES_REQUEST";
export const FETCH_TOTAL_CATEGORIES_SUCCESS = "FETCH_TOTAL_CATEGORIES_SUCCESS";
export const FETCH_TOTAL_CATEGORIES_FAILED = "FETCH_TOTAL_CATEGORIES_FAILED";

export const FETCH_TOTAL_SUBCATEGORIES_REQUEST =
    "FETCH_TOTAL_SUBCATEGORIES_REQUEST";
export const FETCH_TOTAL_SUBCATEGORIES_SUCCESS =
    "FETCH_TOTAL_SUBCATEGORIES_SUCCESS";
export const FETCH_TOTAL_SUBCATEGORIES_FAILED =
    "FETCH_TOTAL_SUBCATEGORIES_FAILED";

export const FETCH_TOTAL_ARTICLES_REQUEST = "FETCH_TOTAL_ARTICLES_REQUEST";
export const FETCH_TOTAL_ARTICLES_SUCCESS = "FETCH_TOTAL_ARTICLES_SUCCESS";
export const FETCH_TOTAL_ARTICLES_FAILED = "FETCH_TOTAL_ARTICLES_FAILED";

export const FETCH_TOTAL_PRODUCTS_REQUEST = "FETCH_TOTAL_PRODUCTS_REQUEST";
export const FETCH_TOTAL_PRODUCTS_SUCCESS = "FETCH_TOTAL_PRODUCTS_SUCCESS";
export const FETCH_TOTAL_PRODUCTS_FAILED = "FETCH_TOTAL_PRODUCTS_FAILED";

export const FETCH_TOTAL_EVENTS_REQUEST = "FETCH_TOTAL_EVENTS_REQUEST";
export const FETCH_TOTAL_EVENTS_SUCCESS = "FETCH_TOTAL_EVENTS_SUCCESS";
export const FETCH_TOTAL_EVENTS_FAILED = "FETCH_TOTAL_EVENTS_FAILED";
