export const FILTER_TABLE_REQUEST = "FILTER_TABLE_REQUEST";
export const FILTER_TABLE_SUCCESS = "FILTER_TABLE_SUCCESS";
export const FILTER_TABLE_FAILED = "FILTER_TABLE_FAILED";

export const SET_PAGE_SIZE = "SET_PAGE_SIZE";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_PARAMS = "SET_PARAMS";
export const SET_PARAM_URL = "SET_PARAM_URL";
export const CLEAR_PARAMS = "CLEAR_PARAMS";
export const SET_TOTAL_RESULT_COUNT = "SET_TOTAL_RESULT_COUNT";
