export const FETCH_SPECIALIZATIONS_REQUEST = "FETCH_SPECIALIZATIONS_REQUEST";
export const FETCH_SPECIALIZATIONS_SUCCESS = "FETCH_SPECIALIZATIONS_SUCCESS";
export const FETCH_SPECIALIZATIONS_FAILED = "FETCH_SPECIALIZATIONS_FAILED";

export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const FETCH_SUBCATEGORIES_REQUEST = "FETCH_SUBCATEGORIES_REQUEST";
export const FETCH_SUBCATEGORIES_SUCCESS = "FETCH_SUBCATEGORIES_SUCCESS";
export const FETCH_SUBCATEGORIES_FAILED = "FETCH_SUBCATEGORIES_FAILED";

export const ADD_SUBCATEGORY_REQUEST = "ADD_SUBCATEGORY_REQUEST";
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_FAILED = "ADD_SUBCATEGORY_FAILED";

export const CREATE_ARTICLE_REQUEST = "CREATE_ARTICLE_REQUEST";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILED = "CREATE_ARTICLE_FAILED";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILED = "UPDATE_ARTICLE_FAILED";

export const ARCHIVE_ARTICLE_REQUEST = "ARCHIVE_ARTICLE_REQUEST";
export const ARCHIVE_ARTICLE_SUCCESS = "ARCHIVE_ARTICLE_SUCCESS";
export const ARCHIVE_ARTICLE_FAILED = "ARCHIVE_ARTICLE_FAILED";

export const FETCH_CURRENT_ARTICLE_REQUEST = "FETCH_CURRENT_ARTICLE_REQUEST";
export const FETCH_CURRENT_ARTICLE_SUCCESS = "FETCH_CURRENT_ARTICLE_SUCCESS";
export const FETCH_CURRENT_ARTICLE_FAILED = "FETCH_CURRENT_ARTICLE_FAILED";

export const CHANGE_ARTICLE_STATUS_REQUEST = "CHANGE_ARTICLE_STATUS_REQUEST";
export const CHANGE_ARTICLE_STATUS_SUCCESS = "CHANGE_ARTICLE_STATUS_SUCCESS";
export const CHANGE_ARTICLE_STATUS_FAILED = "CHANGE_ARTICLE_STATUS_FAILED";

export const CHECK_IMAGE_REQUEST = "CHECK_IMAGE_REQUEST";
export const CHECK_IMAGE_SUCCESS = "CHECK_IMAGE_SUCCESS";
export const CHECK_IMAGE_FAILED = "CHECK_IMAGE_FAILED";

export const SEARCH_TAGS_REQUEST = "SEARCH_TAGS_REQUEST";
export const SEARCH_TAGS_SUCCESS = "SEARCH_TAGS_SUCCESS";
export const SEARCH_TAGS_FAILED = "SEARCH_TAGS_FAILED";

export const FETCH_TAGS_REQUEST = "FETCH_TAGS_REQUEST";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAILED = "FETCH_TAGS_FAILED";

export const SET_STATUS_CHANGE_FORM_DISABLE = "SET_STATUS_CHANGE_FORM_DISABLE";
