export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const CLEAR_ARTICLES = "CLEAR_ARTICLES";
export const ARTICLE_ERROR = "ARTICLE_ERROR";
export const SET_LOADING_ARTICLES = "SET_LOADING_ARTICLES";
