export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";

// Update profile info on profile page
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

// Change passsword on profile page
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

// Request password reset email on forgot password page
export const FORGOT_PASSWORD_EMAIL_REQUEST = "RESET_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_EMAIL_SUCCESS = "FORGOT_PASSWORD_EMAIL_SUCCESS";
export const FORGOT_PASSWORD_EMAIL_FAILED = "FORGOT_PASSWORD_EMAIL_FAILED";

// Verify password reset token on reset password page
export const GET_RESET_PASSWORD_TOKEN_PARAMS =
  "GET_RESET_PASSWORD_TOKEN_PARAMS";
export const VERIFY_RESET_PASSWORD_TOKEN_REQUEST =
  "VERIFY_RESET_PASSWORD_TOKEN_REQUEST";
export const VERIFY_RESET_PASSWORD_TOKEN_SUCCESS =
  "VERIFY_RESET_PASSWORD_TOKEN_SUCCESS";
export const VERIFY_RESET_PASSWORD_TOKEN_FAILED =
  "VERIFY_RESET_PASSWORD_TOKEN_FAILED";

export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";

// Resend password reset email for expired/invalid tokens
export const RESEND_PASSWORD_RESET_EMAIL_LINK_REQUEST =
  "RESEND_PASSWORD_RESET_EMAIL_LINK_REQUEST";
export const RESEND_PASSWORD_RESET_EMAIL_LINK_SUCCESS =
  "RESEND_PASSWORD_RESET_EMAIL_LINK_SUCCESS";
export const RESEND_PASSWORD_RESET_EMAIL_LINK_FAILED =
  "RESEND_PASSWORD_RESET_EMAIL_LINK_FAILED";

export const PASSWORD_NOTIFICATION_REQUEST = "PASSWORD_NOTIFICATION_REQUEST";
export const PASSWORD_NOTIFICATION_SUCCESS = "PASSWORD_NOTIFICATION_SUCCESS";
